name: build-swe-agent
on:
  workflow_dispatch:
  push:
    branches: ["main", "dev"]
    paths:
      - "docker/**"
  pull_request:
    branches: ["main"]
    paths:
      - "docker/**"
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get ACR token
        id: get-acr-token
        run: |
          token=$(az acr login --name crplexicus --expose-token --output tsv --query accessToken)
          echo "::add-mask::$token"
          echo "token=$token" >> $GITHUB_OUTPUT

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: crplexicus.azurecr.io
          username: 00000000-0000-0000-0000-000000000000
          password: ${{ steps.get-acr-token.outputs.token }}
      
      - name: Extract branch name
        id: extract_branch
        run: |
          # Extract the branch name and sanitize it
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          BRANCH_NAME=${BRANCH_NAME//[^a-zA-Z0-9_]/-}
          echo "branch=$BRANCH_NAME" >> $GITHUB_ENV
      
      - name: Build and push swe-agent
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/swe.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            crplexicus.azurecr.io/swe-agent:${{ env.branch }}-${{ github.run_number }}
            crplexicus.azurecr.io/swe-agent:latest
      
      - name: Log out
        if: always()
        run: |
          az logout
          docker logout crplexicus.azurecr.io
